services:
  lucky:
    image: gdy666/lucky:latest
    container_name: lucky
    network_mode: "container:mihomo"
    restart: always
    volumes:
      - ./:/goodluck

networks:
  macvlan:
    external: true